name: Test
version: 1.0
author: icebreaker
main: com.icebreaker.testing.Test

commands:
  class:
    usage: /class
    description: shortcut instead of using portal ( not recommanded )
  feed:
    usage: /feed 
    description: feeds a player
  kit:
    usage: /kit
    description : gives the player some items     
  msg:
    usage: /msg
    description: send messages to players  
  gm:
    usage: /gm
    description : give the gamemenu
  rank:
    usage: /rank
    description: give players ranks
  shout:
    usage: /br
    description: broadcast a message  
  recall:
    usage: /bw
    description: teleports to base after 3 seconds  
  start:
    usage: /start
    description: start the game mode
  build:
    usage: /build
    description: ability to build
  icesay:
    usage: /icesay
    description: idk  
  kirdowsay:
    usage: /kirdowsay
    description: idk  
  ethsay:
    usage: /ethsay
    description: idk      
  wizsay:
    usage: /wizsay
    description: idk   
  jabsay:
    usage: /wizsay
    description: idk   
  souls:
    usage: /souls
    description: kek  
  attackperks:
    usage: attackperks
    description: kek        
    