// 
// Decompiled by Procyon v0.5.36
// 

package com.icebreaker.GUI;

import org.bukkit.DyeColor;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.Inventory;
import java.util.List;
import java.util.ArrayList;
import org.bukkit.inventory.ItemStack;
import org.bukkit.Material;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.ChatColor;
import org.bukkit.Bukkit;
import org.bukkit.entity.HumanEntity;

public class ItemsGUI
{
    public void acrobatItems(final HumanEntity humanEntity) {
        final Inventory invAcro = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invAcro.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invAcro.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invAcro.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invAcro.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invAcro.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invAcro.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item7.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invAcro.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.FISHING_ROD, 1);
        invAcro.setItem(7, item9);
        humanEntity.openInventory(invAcro);
    }
    
    public void endermageItems(final HumanEntity humanEntity) {
        final Inventory invEnder = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invEnder.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invEnder.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invEnder.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invEnder.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invEnder.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invEnder.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invEnder.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.FISHING_ROD, 1);
        invEnder.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.EYE_OF_ENDER, 1);
        final ItemMeta im9 = item10.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Recall" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item10.setItemMeta(im9);
        invEnder.setItem(8, item10);
        humanEntity.openInventory(invEnder);
    }
    
    public void cryoItems(final HumanEntity humanEntity) {
        final Inventory invCryo = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invCryo.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invCryo.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invCryo.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invCryo.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invCryo.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invCryo.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invCryo.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.FISHING_ROD, 1);
        invCryo.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.INK_SACK, 1, (short)DyeColor.LIGHT_BLUE.getDyeData());
        final ItemMeta im9 = item10.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Freeze" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item10.setItemMeta(im9);
        invCryo.setItem(8, item10);
        humanEntity.openInventory(invCryo);
    }
    
    public void pyroItems(final HumanEntity humanEntity) {
        final Inventory invCryo = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invCryo.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invCryo.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invCryo.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invCryo.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invCryo.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invCryo.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invCryo.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.INK_SACK, 1, (short)DyeColor.RED.getDyeData());
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Firestorm" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invCryo.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invCryo.setItem(7, item10);
        humanEntity.openInventory(invCryo);
    }
    
    public void warheadItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.REDSTONE);
        final ItemMeta im9 = item10.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Shield" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item10.setItemMeta(im9);
        invWar.setItem(8, item10);
        humanEntity.openInventory(invWar);
    }
    
    public void sniperItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.GHAST_TEAR);
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Snipe" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invWar.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item10);
        humanEntity.openInventory(invWar);
    }
    
    public void ariesItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.FLINT);
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Chaos" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invWar.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item10);
        humanEntity.openInventory(invWar);
    }
    
    public void hackerItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.EMERALD);
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Hack" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invWar.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item10);
        humanEntity.openInventory(invWar);
    }
    
    public void hunterItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.SHULKER_SHELL);
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Trap" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invWar.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item10);
        humanEntity.openInventory(invWar);
    }
    
    public void mercyItems(final HumanEntity humanEntity) {
        final Inventory invWar = Bukkit.getServer().createInventory((InventoryHolder)null, 18, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Class Items").toString());
        final ItemStack item2 = new ItemStack(Material.LEATHER_HELMET, 1);
        final ItemMeta im2 = item2.getItemMeta();
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(ChatColor.GOLD + "Soulbound Item");
        im2.setLore((List)lore2);
        item2.setItemMeta(im2);
        invWar.setItem(0, item2);
        final ItemStack item3 = new ItemStack(Material.LEATHER_BOOTS, 1);
        final ItemMeta im3 = item3.getItemMeta();
        final ArrayList<String> lore3 = new ArrayList<String>();
        lore3.add(ChatColor.GOLD + "Soulbound Item");
        im3.setLore((List)lore3);
        item3.setItemMeta(im3);
        invWar.setItem(3, item3);
        final ItemStack item4 = new ItemStack(Material.LEATHER_CHESTPLATE, 1);
        final ItemMeta im4 = item4.getItemMeta();
        final ArrayList<String> lore4 = new ArrayList<String>();
        lore4.add(ChatColor.GOLD + "Soulbound Item");
        im4.setLore((List)lore3);
        item4.setItemMeta(im3);
        invWar.setItem(1, item4);
        final ItemStack item5 = new ItemStack(Material.LEATHER_LEGGINGS, 1);
        final ItemMeta im5 = item4.getItemMeta();
        final ArrayList<String> lore5 = new ArrayList<String>();
        lore5.add(ChatColor.GOLD + "Soulbound Item");
        im5.setLore((List)lore5);
        item5.setItemMeta(im5);
        invWar.setItem(2, item5);
        final ItemStack item6 = new ItemStack(Material.WOOD_SWORD, 1);
        final ItemMeta im6 = item6.getItemMeta();
        final ArrayList<String> lore6 = new ArrayList<String>();
        lore6.add(ChatColor.GOLD + "Soulbound Item");
        im6.setLore((List)lore6);
        item6.setItemMeta(im6);
        invWar.setItem(4, item6);
        final ItemStack item7 = new ItemStack(Material.STONE_PICKAXE, 1);
        final ItemMeta im7 = item7.getItemMeta();
        final ArrayList<String> lore7 = new ArrayList<String>();
        lore7.add(ChatColor.GOLD + "Soulbound Item");
        im7.setLore((List)lore7);
        item7.setItemMeta(im7);
        invWar.setItem(5, item7);
        final ItemStack item8 = new ItemStack(Material.WOOD_AXE, 1);
        final ItemMeta im8 = item8.getItemMeta();
        final ArrayList<String> lore8 = new ArrayList<String>();
        lore8.add(ChatColor.GOLD + "Soulbound Item");
        im8.setLore((List)lore8);
        item8.setItemMeta(im8);
        invWar.setItem(6, item8);
        final ItemStack item9 = new ItemStack(Material.TOTEM);
        final ItemMeta im9 = item9.getItemMeta();
        im9.setDisplayName(ChatColor.AQUA + "Revive" + ChatColor.GREEN + ChatColor.BOLD + " READY");
        final ArrayList<String> lore9 = new ArrayList<String>();
        lore9.add(new StringBuilder().append(ChatColor.DARK_PURPLE).append(ChatColor.BOLD).append("Class Item").toString());
        im9.setLore((List)lore9);
        item9.setItemMeta(im9);
        invWar.setItem(8, item9);
        final ItemStack item10 = new ItemStack(Material.FISHING_ROD, 1);
        invWar.setItem(7, item10);
        humanEntity.openInventory(invWar);
    }
}
