// 
// Decompiled by Procyon v0.5.36
// 

package com.icebreaker.mechanics;

import org.bukkit.event.EventHandler;
import org.bukkit.entity.HumanEntity;
import org.bukkit.Sound;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.Inventory;
import java.util.List;
import java.util.ArrayList;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.Material;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.ChatColor;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;

public class EnchRecipes implements Listener
{
    public void recipesPage1(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 1").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.IRON_BLOCK, 1);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.FEATHER, 1);
        final ItemMeta im23 = item23.getItemMeta();
        im23.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Chicken Feather").toString());
        im23.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore23 = new ArrayList<String>();
        lore23.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Used for crafting powerful item!").toString());
        im23.setLore((List)lore23);
        item23.setItemMeta(im23);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.ELYTRA, 1);
        final ItemMeta im24 = item26.getItemMeta();
        im24.setDisplayName(new StringBuilder().append(ChatColor.AQUA).append(ChatColor.BOLD).append("Gliders").toString());
        im24.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        im24.setUnbreakable(true);
        final ArrayList<String> lore24 = new ArrayList<String>();
        lore24.add(ChatColor.WHITE + "Grants the ability to surf the skies");
        im24.setLore((List)lore24);
        item26.setItemMeta(im24);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im25 = item28.getItemMeta();
        im25.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 2").toString());
        im25.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im25);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.GOLD_BLOCK, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.IRON_INGOT, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage2(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 2").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.SUGAR_CANE, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.STICK, 1);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.STRING, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im5 = item20.getItemMeta();
        im5.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 1").toString());
        im5.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im5);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.STICK, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.SUGAR_CANE, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.STRING, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.BOW, 1);
        final ItemMeta im6 = item26.getItemMeta();
        im6.setDisplayName(new StringBuilder().append(ChatColor.DARK_GREEN).append(ChatColor.BOLD).append("Bow").toString());
        im6.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item26.setItemMeta(im6);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im7 = item28.getItemMeta();
        im7.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 3").toString());
        im7.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im7);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.SUGAR_CANE, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.STICK, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.STRING, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage3(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 3").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.AIR, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.FLINT, 1);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.AIR, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im5 = item20.getItemMeta();
        im5.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 2").toString());
        im5.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im5);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.AIR, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.STICK, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.AIR, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.ARROW, 3);
        final ItemMeta im6 = item26.getItemMeta();
        im6.setDisplayName(new StringBuilder().append(ChatColor.DARK_GREEN).append(ChatColor.BOLD).append("Arrow").toString());
        im6.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item26.setItemMeta(im6);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im7 = item28.getItemMeta();
        im7.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 4").toString());
        im7.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im7);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.AIR, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.SUGAR_CANE, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.AIR, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage4(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 4").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.AIR, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.AIR, 1);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.AIR, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im5 = item20.getItemMeta();
        im5.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 3").toString());
        im5.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im5);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.AIR, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.IRON_PICKAXE, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.FEATHER, 1);
        final ItemMeta im6 = item24.getItemMeta();
        im6.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Chicken Feather").toString());
        im6.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore24 = new ArrayList<String>();
        lore24.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Used for crafting powerful item!").toString());
        im6.setLore((List)lore24);
        item24.setItemMeta(im6);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.IRON_PICKAXE, 1);
        final ItemMeta im7 = item26.getItemMeta();
        im7.setDisplayName(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Ancient Pickaxe").toString());
        im7.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        im7.setUnbreakable(true);
        final ArrayList<String> lore25 = new ArrayList<String>();
        lore25.add(ChatColor.WHITE + "Used the mine to rarest minerals");
        im7.setLore((List)lore25);
        item26.setItemMeta(im7);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im8 = item28.getItemMeta();
        im8.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 5").toString());
        im8.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im8);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.AIR, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.AIR, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.AIR, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage5(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 5").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.AIR, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.SKULL_ITEM, 1, (short)1);
        final ItemMeta im14 = item14.getItemMeta();
        im14.setDisplayName(new StringBuilder().append(ChatColor.DARK_RED).append(ChatColor.BOLD).append("Tribal Mask").toString());
        im14.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore14 = new ArrayList<String>();
        lore14.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Grants unlimited power to who wears it!").toString());
        im14.setLore((List)lore14);
        item14.setItemMeta(im14);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.AIR, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im15 = item20.getItemMeta();
        im15.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 4").toString());
        im15.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im15);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.DIAMOND_BLOCK, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.DIAMOND_BLOCK, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.DIAMOND_BLOCK, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.NETHER_STAR, 1);
        final ItemMeta im16 = item26.getItemMeta();
        im16.setDisplayName(new StringBuilder().append(ChatColor.AQUA).append(ChatColor.BOLD).append("Ancient Revival").toString());
        im16.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item26.setItemMeta(im16);
        final ArrayList<String> lore15 = new ArrayList<String>();
        lore15.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Used to revive ancient mythical weapons").toString());
        im16.setLore((List)lore15);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im17 = item28.getItemMeta();
        im17.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 6").toString());
        im17.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im17);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.AIR, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.DIAMOND_BLOCK, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.AIR, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage6(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 6").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.RAW_FISH, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.SKULL_ITEM, 1, (short)1);
        final ItemMeta im14 = item14.getItemMeta();
        im14.setDisplayName(new StringBuilder().append(ChatColor.DARK_RED).append(ChatColor.BOLD).append("Tribal Mask").toString());
        im14.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore14 = new ArrayList<String>();
        lore14.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Grants unlimited power to who wears it!").toString());
        im14.setLore((List)lore14);
        item14.setItemMeta(im14);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.RAW_FISH, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im15 = item20.getItemMeta();
        im15.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 5").toString());
        im15.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im15);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.RAW_FISH, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.DIAMOND_CHESTPLATE, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.RAW_FISH, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.DIAMOND_CHESTPLATE, 1);
        final ItemMeta im16 = item26.getItemMeta();
        im16.setDisplayName(new StringBuilder().append(ChatColor.AQUA).append(ChatColor.BOLD).append("Diving suit").toString());
        im16.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore15 = new ArrayList<String>();
        lore15.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Used to dive into deep oceans.").toString());
        im16.setLore((List)lore15);
        item26.setItemMeta(im16);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im17 = item28.getItemMeta();
        im17.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 7").toString());
        im17.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item28.setItemMeta(im17);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.PRISMARINE_CRYSTALS, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.FEATHER, 1);
        final ItemMeta im18 = item32.getItemMeta();
        im18.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Chicken Feather").toString());
        im18.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore16 = new ArrayList<String>();
        lore16.add(new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Used for crafting powerful item!").toString());
        im18.setLore((List)lore16);
        item32.setItemMeta(im18);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.PRISMARINE_CRYSTALS, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    public void recipesPage7(final Player p) {
        final Inventory page1 = Bukkit.getServer().createInventory((InventoryHolder)null, 45, new StringBuilder().append(ChatColor.WHITE).append(ChatColor.BOLD).append("Recipes: Page 7").toString());
        final ItemStack item0 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(0, item0);
        final ItemStack item2 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(1, item2);
        final ItemStack item3 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(2, item3);
        final ItemStack item4 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(3, item4);
        final ItemStack item5 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(4, item5);
        final ItemStack item6 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(5, item6);
        final ItemStack item7 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(6, item7);
        final ItemStack item8 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item8);
        final ItemStack item9 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(7, item9);
        final ItemStack item10 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(8, item10);
        final ItemStack item11 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(9, item11);
        final ItemStack item12 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(10, item12);
        final ItemStack item13 = new ItemStack(Material.AIR, 1);
        page1.setItem(11, item13);
        final ItemStack item14 = new ItemStack(Material.PRISMARINE_SHARD, 1);
        final ItemMeta im = item14.getItemMeta();
        im.setDisplayName(new StringBuilder().append(ChatColor.AQUA).append(ChatColor.BOLD).append("Poseidon Shard").toString());
        im.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore = new ArrayList<String>();
        lore.add(new StringBuilder().append(ChatColor.DARK_RED).append(ChatColor.MAGIC).append(ChatColor.BOLD).append("dfgtebdszd").toString());
        im.setLore((List)lore);
        item14.setItemMeta(im);
        page1.setItem(12, item14);
        final ItemStack item15 = new ItemStack(Material.AIR, 1);
        page1.setItem(13, item15);
        final ItemStack item16 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(14, item16);
        final ItemStack item17 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(15, item17);
        final ItemStack item18 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(16, item18);
        final ItemStack item19 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(17, item19);
        final ItemStack item20 = new ItemStack(Material.ARROW, 1);
        final ItemMeta im2 = item20.getItemMeta();
        im2.setDisplayName(new StringBuilder().append(ChatColor.GOLD).append(ChatColor.BOLD).append("Page 6").toString());
        im2.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        item20.setItemMeta(im2);
        page1.setItem(26, item20);
        page1.setItem(18, item20);
        final ItemStack item21 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(19, item21);
        final ItemStack item22 = new ItemStack(Material.AIR, 1);
        page1.setItem(20, item22);
        final ItemStack item23 = new ItemStack(Material.STICK, 1);
        page1.setItem(21, item23);
        final ItemStack item24 = new ItemStack(Material.AIR, 1);
        page1.setItem(22, item24);
        final ItemStack item25 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(23, item25);
        final ItemStack item26 = new ItemStack(Material.DIAMOND_SPADE, 1);
        final ItemMeta im3 = item26.getItemMeta();
        im3.setDisplayName(new StringBuilder().append(ChatColor.AQUA).append(ChatColor.BOLD).append("Poseidon Spear").toString());
        im3.addItemFlags(new ItemFlag[] { ItemFlag.HIDE_ATTRIBUTES });
        final ArrayList<String> lore2 = new ArrayList<String>();
        lore2.add(new StringBuilder().append(ChatColor.DARK_RED).append(ChatColor.MAGIC).append(ChatColor.BOLD).append("dfgtebdszd").toString());
        im3.setLore((List)lore2);
        item26.setItemMeta(im3);
        page1.setItem(24, item26);
        final ItemStack item27 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(25, item27);
        final ItemStack item28 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(26, item28);
        final ItemStack item29 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(27, item29);
        final ItemStack item30 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(28, item30);
        final ItemStack item31 = new ItemStack(Material.AIR, 1);
        page1.setItem(29, item31);
        final ItemStack item32 = new ItemStack(Material.STICK, 1);
        page1.setItem(30, item32);
        final ItemStack item33 = new ItemStack(Material.AIR, 1);
        page1.setItem(31, item33);
        final ItemStack item34 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(32, item34);
        final ItemStack item35 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(33, item35);
        final ItemStack item36 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(34, item36);
        final ItemStack item37 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(35, item37);
        final ItemStack item38 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item38);
        final ItemStack item39 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(36, item39);
        final ItemStack item40 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(37, item40);
        final ItemStack item41 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(38, item41);
        final ItemStack item42 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(39, item42);
        final ItemStack item43 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(40, item43);
        final ItemStack item44 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(41, item44);
        final ItemStack item45 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(42, item45);
        final ItemStack item46 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(43, item46);
        final ItemStack item47 = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
        page1.setItem(44, item47);
        p.openInventory(page1);
    }
    
    @EventHandler
    public void onInvClick(final InventoryClickEvent e) {
        final HumanEntity p = e.getWhoClicked();
        if (!e.getInventory().getTitle().contains("Recipes")) {
            return;
        }
        if (e.getCurrentItem() == null) {
            return;
        }
        if (!e.getCurrentItem().hasItemMeta()) {
            return;
        }
        if (!e.getCurrentItem().getItemMeta().hasDisplayName()) {
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("1")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage1(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("7")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage7(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("2")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage2(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("3")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage3(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("4")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage4(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("5")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage5(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
            return;
        }
        if (e.getCurrentItem().getItemMeta().getDisplayName().contains("6")) {
            e.setCancelled(true);
            final Player player = (Player)p;
            this.recipesPage6(player);
            player.playSound(player.getLocation(), Sound.BLOCK_NOTE_PLING, 10.0f, 1.0f);
        }
    }
}
